/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
      _key: string
    }
>

export type Info = {
  _id: string
  _type: 'info'
  _createdAt: string
  _updatedAt: string
  _rev: string
  brandName?: string
  address?: string
  phone?: string
  email?: string
  whatsapp?: string
  instagram?: string
  terms?: string
  privacy?: string
}

export type DestinationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'destination'
}

export type ItineraryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'itinerary'
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  title?: string
  quote?: string
  featured?: boolean
  destination?: DestinationReference
  itinerary?: ItineraryReference
  headshot?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Journal = {
  _id: string
  _type: 'journal'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  excerpt: string
  content?: BlockContent
  publishedAt: string
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  itinerary?: ItineraryReference
  slug: Slug
}

export type FeatureReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'feature'
}

export type ThemeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'theme'
}

export type CuratorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'curator'
}

export type StayReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'stay'
}

export type Itinerary = {
  _id: string
  _type: 'itinerary'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  tagline: string
  days?: number
  price: string
  featured?: boolean
  overview?: string
  schedule?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'segment'
    _key: string
  }>
  foods?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'food'
    _key: string
  }>
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  features: Array<
    {
      _key: string
    } & FeatureReference
  >
  destinations?: Array<
    {
      _key: string
    } & DestinationReference
  >
  themes: Array<
    {
      _key: string
    } & ThemeReference
  >
  curator?: CuratorReference
  stays?: Array<
    {
      _key: string
    } & StayReference
  >
  slug: Slug
}

export type Stay = {
  _id: string
  _type: 'stay'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  description?: string
  type?: 'Resort' | 'Boutique' | 'Glamping' | 'Villa' | 'Palace' | 'Lodge'
  destination?: DestinationReference
  website?: string
  cover?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  slug: Slug
}

export type Destination = {
  _id: string
  _type: 'destination'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  country: string
  tagline?: string
  appeal?: string
  attractions?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'attraction'
    _key: string
  }>
  activities?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'activity'
    _key: string
  }>
  foods?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'food'
    _key: string
  }>
  commentary?: string
  featured?: boolean
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  themes?: Array<
    {
      _key: string
    } & ThemeReference
  >
  slug: Slug
}

export type Curator = {
  _id: string
  _type: 'curator'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  title?: string
  email?: string
  bio?: string
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  slug: Slug
}

export type Feature = {
  _id: string
  _type: 'feature'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  blurb?: string
  slug: Slug
}

export type Theme = {
  _id: string
  _type: 'theme'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  description: string
  slug: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Info
  | DestinationReference
  | ItineraryReference
  | Testimonial
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | Journal
  | FeatureReference
  | ThemeReference
  | CuratorReference
  | StayReference
  | Itinerary
  | Stay
  | Destination
  | Curator
  | Feature
  | Theme
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/components/destinations/DestinationPolaroid.astro
// Variable: query
// Query: *[_type == "destination" && slug.current == $slug][0] {    "images": (      attractions[].image {        ...,        "dimensions": asset->metadata.dimensions      }      + activities[].image {        ...,        "dimensions": asset->metadata.dimensions      }      + foods[].image {        ...,        "dimensions": asset->metadata.dimensions      }    )  }
export type QueryResult = {
  images: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    dimensions: SanityImageDimensions | null
  }> | null
} | null

// Source: src/pages/destinations/[slug].astro
// Variable: destinationSlugsQuery
// Query: *[_type == "destination"]{ slug }
export type DestinationSlugsQueryResult = Array<{
  slug: Slug
}>

// Source: src/pages/destinations/[slug].astro
// Variable: destinationQuery
// Query: *[_type=="destination" && slug.current == $slug][0] {      ...,      cover {        ...,        "lqip": asset->metadata.lqip      },      themes[]->,      "testimonials": *[_type == 'testimonial' && references(^._id)],      "itineraries": *[_type == 'itinerary' && references(^._id)]   {    slug,    title,    tagline,    cover,    price,    themes[0..2]->  }  }
export type DestinationQueryResult = {
  _id: string
  _type: 'destination'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  country: string
  tagline?: string
  appeal?: string
  attractions?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'attraction'
    _key: string
  }>
  activities?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'activity'
    _key: string
  }>
  foods?: Array<{
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    featured?: boolean
    _type: 'food'
    _key: string
  }>
  commentary?: string
  featured?: boolean
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    lqip: string | null
  }
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  themes: Array<{
    _id: string
    _type: 'theme'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name: string
    description: string
    slug: Slug
  }> | null
  slug: Slug
  testimonials: Array<{
    _id: string
    _type: 'testimonial'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name?: string
    title?: string
    quote?: string
    featured?: boolean
    destination?: DestinationReference
    itinerary?: ItineraryReference
    headshot?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    slug: Slug
  }>
  itineraries: Array<{
    slug: Slug
    title: string
    tagline: string
    cover: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    price: string
    themes: Array<{
      _id: string
      _type: 'theme'
      _createdAt: string
      _updatedAt: string
      _rev: string
      name: string
      description: string
      slug: Slug
    }>
  }>
} | null

// Source: src/pages/destinations/index.astro
// Variable: destinationsIndexQuery
// Query: {  "destinations": *[_type == "destination"] {    cover,    name,    slug,    country,    "themes": coalesce(themes[]-> {_id,name}, [])  },  "featuredDests": *[_type == "destination" && featured]  {  cover,  portrait,  name,  country,  commentary,  slug  },  "themes": *[_type == "theme"]  }
export type DestinationsIndexQueryResult = {
  destinations: Array<{
    cover: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    name: string
    slug: Slug
    country: string
    themes:
      | Array<{
          _id: string
          name: string
        }>
      | Array<never>
  }>
  featuredDests: Array<{
    cover: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    portrait: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
    name: string
    country: string
    commentary: string | null
    slug: Slug
  }>
  themes: Array<{
    _id: string
    _type: 'theme'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name: string
    description: string
    slug: Slug
  }>
}

// Source: src/pages/index.astro
// Variable: indexPageQuery
// Query: {  "featuredDestinations": *[_type == "destination" && featured] {    cover,    "attractions": attractions[featured] {      ...,      "location": ^.name,      "country": ^.country    }  },  "featuredItineraries": *[_type == "itinerary" && featured] {  slug,  cover,  ...select(defined(portrait) => { portrait }),  title,  tagline,  "overview": coalesce(overview, ""),  "destinations": coalesce(count(destinations), 0),  "days": coalesce(count(schedule), 0)},  }
export type IndexPageQueryResult = {
  featuredDestinations: Array<{
    cover: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    attractions: Array<{
      title: string
      body?: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }>
      image: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
      }
      featured?: boolean
      _type: 'attraction'
      _key: string
      location: string
      country: string
    }> | null
  }>
  featuredItineraries: Array<{
    slug: Slug
    cover: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    portrait: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    title: string
    tagline: string
    overview: string | ''
    destinations: number | 0
    days: number | 0
  }>
}

// Source: src/pages/itineraries/index.astro
// Variable: itinerariesIndexQuery
// Query: *[_type == 'itinerary']   {    slug,    title,    tagline,    cover,    price,    themes[0..2]->  }
export type ItinerariesIndexQueryResult = Array<{
  slug: Slug
  title: string
  tagline: string
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  price: string
  themes: Array<{
    _id: string
    _type: 'theme'
    _createdAt: string
    _updatedAt: string
    _rev: string
    name: string
    description: string
    slug: Slug
  }>
}>

// Source: src/pages/journal/[slug].astro
// Variable: journalSlugsQuery
// Query: *[_type == "journal"]{ slug }
export type JournalSlugsQueryResult = Array<{
  slug: Slug
}>

// Source: src/pages/journal/[slug].astro
// Variable: journalQuery
// Query: *[_type == 'journal' && slug.current == $slug][0] {  ..., itinerary-> {  slug,  title,  curator-> {    slug,    name,    portrait   } }, "related": *[_type == 'journal'&&_id != ^._id] | order(   select(     publishedAt > ^.publishedAt => publishedAt - ^.publishedAt,     ^.publishedAt - publishedAt   ) )[0...2] {  slug,  cover,  title,  publishedAt  }  }
export type JournalQueryResult = {
  _id: string
  _type: 'journal'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  excerpt: string
  content?: BlockContent
  publishedAt: string
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  itinerary: {
    slug: Slug
    title: string
    curator: {
      slug: Slug
      name: string | null
      portrait: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
      } | null
    } | null
  } | null
  slug: Slug
  related: Array<{
    slug: Slug
    cover: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    title: string
    publishedAt: string
  }>
} | null

// Source: src/pages/journal/index.astro
// Variable: journalIndexQuery
// Query: *[_type == 'journal'] | order(publishedAt desc) {  slug,  cover,  title,  publishedAt  }
export type JournalIndexQueryResult = Array<{
  slug: Slug
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  title: string
  publishedAt: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "destination" && slug.current == $slug][0] {\n    "images": (\n      attractions[].image {\n        ...,\n        "dimensions": asset->metadata.dimensions\n      }\n      + activities[].image {\n        ...,\n        "dimensions": asset->metadata.dimensions\n      }\n      + foods[].image {\n        ...,\n        "dimensions": asset->metadata.dimensions\n      }\n    )\n  }\n': QueryResult
    '*[_type == "destination"]{ slug }': DestinationSlugsQueryResult
    '*[_type=="destination" && slug.current == $slug][0] {\n      ...,\n      cover {\n        ...,\n        "lqip": asset->metadata.lqip\n      },\n      themes[]->,\n      "testimonials": *[_type == \'testimonial\' && references(^._id)],\n      "itineraries": *[_type == \'itinerary\' && references(^._id)] \n  {\n    slug,\n    title,\n    tagline,\n    cover,\n    price,\n    themes[0..2]->\n  }\n  \n}': DestinationQueryResult
    '{\n  "destinations": *[_type == "destination"] {\n    cover,\n    name,\n    slug,\n    country,\n    "themes": coalesce(themes[]-> {_id,name}, [])\n  },\n  "featuredDests": *[_type == "destination" && featured]  {\n  cover,\n  portrait,\n  name,\n  country,\n  commentary,\n  slug\n  },\n  "themes": *[_type == "theme"]\n  }': DestinationsIndexQueryResult
    '{\n  "featuredDestinations": *[_type == "destination" && featured] {\n    cover,\n    "attractions": attractions[featured] {\n      ...,\n      "location": ^.name,\n      "country": ^.country\n    }\n  },\n  "featuredItineraries": *[_type == "itinerary" && featured] \n{\n  slug,\n  cover,\n  ...select(defined(portrait) => { portrait }),\n  title,\n  tagline,\n  "overview": coalesce(overview, ""),\n  "destinations": coalesce(count(destinations), 0),\n  "days": coalesce(count(schedule), 0)\n}\n,\n  }': IndexPageQueryResult
    " *[_type == 'itinerary'] \n  {\n    slug,\n    title,\n    tagline,\n    cover,\n    price,\n    themes[0..2]->\n  }\n  ": ItinerariesIndexQueryResult
    '*[_type == "journal"]{ slug }': JournalSlugsQueryResult
    "*[_type == 'journal' && slug.current == $slug][0] {\n  ...,\n itinerary-> {\n  slug,\n  title,\n  curator-> {\n    slug,\n    name,\n    portrait\n   }\n },\n \"related\": *[_type == 'journal'&&_id != ^._id] | order(\n   select(\n     publishedAt > ^.publishedAt => publishedAt - ^.publishedAt,\n     ^.publishedAt - publishedAt\n   )\n )[0...2] {\n  slug,\n  cover,\n  title,\n  publishedAt\n  }\n  }": JournalQueryResult
    "*[_type == 'journal'] | order(publishedAt desc) {\n  slug,\n  cover,\n  title,\n  publishedAt\n  }": JournalIndexQueryResult
  }
}
